spring:
  application:
    name: probe-service
  register-center:
    hosts:
      - 127.0.0.1:2181
      - 127.0.0.1:2181
    base-path: /probe-service
    register-center-type: ZOOKEEPER
  netty-server:
    host-name: 127.0.0.1
    port: 12181