server:
  port: 10080

spring:
  application:
    name: probe-client
  register-center:
    hosts:
      - 192.168.200.11:2181
      - 192.168.200.12:2181
      - 192.168.200.13:2181
    base-path: /probe-service
    register-center-type: ZOOKEEPER
  netty-server:
    host-name: 127.0.0.1
    port: 12181