spring:
  application:
    name: probe-services
  register-center:
    hosts:  #注册中心列表,内网ip
      - localhost:2181
      - localhost:2182
      - localhost:2183
    base-path: /probe-services
    register-center-type: ZOOKEEPER
  netty-server:
    ip-addr: 127.0.0.1  #服务所在的服务器的内网ip
    port: 12181
    select-strategy: ROUNDROBIN