server:
  port: 10080

spring:
  application:
    name: probe-client
  register-center:
    hosts: #注册中心列表,内网ip
      - localhost:2181
      - localhost:2182
      - localhost:2183
    base-path: /probe-services
    register-center-type: ZOOKEEPER
    select-strategy: ROUNDROBIN
  netty-server:
    select-strategy: ROUNDROBIN