server:
  port: 10080 #对外提供服务的端口

spring:
  application:
    name: probe-client #服务名称
  register-center:
    hosts: #注册中心列表,内网ip
      - localhost:2181
      - localhost:2182
      - localhost:2183
    base-path: /probe-services #zookeeper注册中心的basePath
    register-center-type: ZOOKEEPER #注册中心类型支持ZOOKEEPER、CONSUL
    select-strategy: ROUNDROBIN #选择注册中心时负载均衡策略
  netty-server:
    select-strategy: ROUNDROBIN #服务发现时,负载均衡的类型(选择具体服务器ip、端口)